/**
 * HTML report generator.
 *
 * Standalone HTML file with embedded CSS + tiny vanilla-JS sorter. No external
 * deps, so the file can be opened from the filesystem or emailed as an
 * attachment.
 */

import type {
  AiTool,
  PortfolioReport,
  PortfolioSummary,
  RepoAnalysis,
  Tier,
} from "../types.js";

export function renderHtmlReport(report: PortfolioReport): string {
  const { summary, repos } = report;
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Portfolio Scan — ${escapeHtml(summary.username)} — ${escapeHtml(summary.scannedAt)}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>${styles()}</style>
</head>
<body>
  <header>
    <h1>Portfolio Scan</h1>
    <p class="meta">
      <strong>@${escapeHtml(summary.username)}</strong> ·
      ${escapeHtml(summary.scannedAt)} ·
      ${summary.totalRepos} repos scanned
    </p>
  </header>

  <section>
    <h2>Summary</h2>
    ${renderTierCards(summary)}
    <div class="next-action">
      <strong>Suggested next action:</strong>
      ${escapeHtml(summary.suggestedNextAction)}
    </div>
    <p class="totals">
      Total estimated hours to resume Tier B/C repos:
      <strong>${summary.totalEstimatedHoursToResume}h</strong>
    </p>
  </section>

  ${renderInsightsSection(summary)}
  ${renderToolCoverageSection(summary)}
  ${renderRepoTable(repos)}
  ${renderRepoDetail(repos)}

  <footer>
    <p>
      Generated by
      <a href="https://github.com/ereztash/lessons/tree/main/saas/scanner">PortfolioPilot Scanner</a>
      v0.1.0. Algorithms documented in
      <code>/products/playbooks/four-feature-tier-classifier.md</code>.
    </p>
  </footer>

  <script>${clientScript()}</script>
</body>
</html>
`;
}

// ---------------------------------------------------------------------------
// sections
// ---------------------------------------------------------------------------

function renderTierCards(s: PortfolioSummary): string {
  const cards: { tier: Tier; label: string; sub: string }[] = [
    { tier: "A", label: "A", sub: "Managed system" },
    { tier: "B", label: "B", sub: "Developing" },
    { tier: "C", label: "C", sub: "Prototype-stalled" },
    { tier: "D", label: "D", sub: "Template skeleton" },
  ];
  return `<div class="tier-grid">${cards
    .map(
      (c) => `
    <div class="tier-card tier-${c.tier}">
      <div class="tier-count">${s.countsByTier[c.tier]}</div>
      <div class="tier-label">Tier ${c.label}</div>
      <div class="tier-sub">${c.sub}</div>
    </div>`,
    )
    .join("")}</div>`;
}

function renderInsightsSection(s: PortfolioSummary): string {
  if (s.insights.length === 0) return "";
  return `
  <section>
    <h2>Cross-repo insights</h2>
    <ul class="insights">
      ${s.insights.map((i) => `<li>${escapeHtml(i)}</li>`).join("")}
    </ul>
  </section>`;
}

function renderToolCoverageSection(s: PortfolioSummary): string {
  const entries = (Object.entries(s.reposByAiTool) as [AiTool, string[]][]).filter(
    ([, repos]) => repos.length > 0,
  );
  if (entries.length === 0) return "";
  return `
  <section>
    <h2>AI tool coverage</h2>
    <table class="tool-table">
      <thead><tr><th>Tool</th><th>Repos</th><th>Names</th></tr></thead>
      <tbody>
        ${entries
          .map(
            ([tool, repos]) => `
          <tr>
            <td><span class="tool-pill tool-${tool}">${tool}</span></td>
            <td>${repos.length}</td>
            <td>${repos.map((r) => `<code>${escapeHtml(r)}</code>`).join(", ")}</td>
          </tr>`,
          )
          .join("")}
      </tbody>
    </table>
  </section>`;
}

function renderRepoTable(repos: RepoAnalysis[]): string {
  const tierOrder: Record<Tier, number> = { A: 0, B: 1, C: 2, D: 3 };
  const sorted = [...repos].sort((a, b) => {
    if (tierOrder[a.tier.tier] !== tierOrder[b.tier.tier]) {
      return tierOrder[a.tier.tier] - tierOrder[b.tier.tier];
    }
    return b.tier.score - a.tier.score;
  });

  return `
  <section>
    <h2>All repos</h2>
    <p class="hint">Click a column header to sort.</p>
    <table id="repos-table" class="repos-table">
      <thead>
        <tr>
          <th data-sort="string">Repo</th>
          <th data-sort="string">Tier</th>
          <th data-sort="number">Score</th>
          <th data-sort="number">Days since commit</th>
          <th data-sort="number">Publish-btn</th>
          <th data-sort="number">Resume</th>
          <th data-sort="number">Commits</th>
          <th data-sort="number">PRs</th>
          <th data-sort="string">AI tools</th>
        </tr>
      </thead>
      <tbody>
        ${sorted
          .map((r) => {
            const tools = r.aiDiversity.toolsDetected.join(", ") || "—";
            const resume = r.resumption.applicable
              ? `${r.resumption.score}${r.resumption.strongCandidate ? " ★" : ""}`
              : "—";
            const pb = `${r.publishButton.score}${r.publishButton.flagged ? " ⚑" : ""}`;
            return `<tr class="row-tier-${r.tier.tier}">
              <td><a href="#repo-${escapeAttr(r.metadata.name)}"><code>${escapeHtml(r.metadata.name)}</code></a></td>
              <td><span class="tier-pill tier-${r.tier.tier}">${r.tier.tier}</span></td>
              <td>${r.tier.score}/4</td>
              <td>${r.commits.daysSinceLastCommit}</td>
              <td>${pb}</td>
              <td>${resume}</td>
              <td>${r.commits.buckets.total}</td>
              <td>${r.prs.count}</td>
              <td>${escapeHtml(tools)}</td>
            </tr>`;
          })
          .join("")}
      </tbody>
    </table>
  </section>`;
}

function renderRepoDetail(repos: RepoAnalysis[]): string {
  const tierOrder: Record<Tier, number> = { A: 0, B: 1, C: 2, D: 3 };
  const sorted = [...repos].sort((a, b) => {
    if (tierOrder[a.tier.tier] !== tierOrder[b.tier.tier]) {
      return tierOrder[a.tier.tier] - tierOrder[b.tier.tier];
    }
    return b.tier.score - a.tier.score;
  });
  return `
  <section>
    <h2>Per-repo detail</h2>
    ${sorted.map((r) => renderSingleRepo(r)).join("")}
  </section>`;
}

function renderSingleRepo(r: RepoAnalysis): string {
  const b = r.commits.buckets;
  const bucketBits: string[] = [];
  const push = (label: string, n: number): void => {
    if (n > 0) bucketBits.push(`${label} ${n}`);
  };
  push("human", b.human);
  push("claude", b.claude);
  push("claude-coauthored", b["claude-coauthored"]);
  push("cursor", b.cursor);
  push("lovable", b.lovable);
  push("gpt-engineer", b["gpt-engineer"]);
  push("bolt", b["bolt-bot"]);
  push("v0", b["v0-bot"]);
  push("codex", b.codex);
  push("copilot", b.copilot);
  push("other-bot", b["bot-other"]);

  return `
  <article class="repo-detail" id="repo-${escapeAttr(r.metadata.name)}">
    <h3>
      <code>${escapeHtml(r.metadata.name)}</code>
      <span class="tier-pill tier-${r.tier.tier}">Tier ${r.tier.tier} (${r.tier.score}/4)</span>
    </h3>
    ${r.metadata.description ? `<p class="repo-desc">${escapeHtml(r.metadata.description)}</p>` : ""}
    <p class="repo-meta">
      <a href="${escapeAttr(r.metadata.htmlUrl)}">${escapeHtml(r.metadata.htmlUrl)}</a><br>
      Default branch <code>${escapeHtml(r.metadata.defaultBranch)}</code>
      · Private: ${r.metadata.isPrivate ? "yes" : "no"}
      · Fork: ${r.metadata.isFork ? "yes" : "no"}
      · Archived: ${r.metadata.isArchived ? "yes" : "no"}<br>
      Last commit: ${escapeHtml(r.commits.lastCommitDate ?? "n/a")}
      (${r.commits.daysSinceLastCommit} days ago)
    </p>
    <p class="rationale"><strong>Tier rationale:</strong> ${escapeHtml(r.tier.rationale)}</p>

    <table class="feature-table">
      <tr>
        <th>Feature</th><th>Status</th>
      </tr>
      <tr>
        <td>Non-template deps</td>
        <td>${r.tier.features.hasNonTemplateDeps ? "yes" : "no"}${
          r.pkg.domainSpecificDeps.length > 0
            ? ` (${escapeHtml(r.pkg.domainSpecificDeps.slice(0, 5).join(", "))}${r.pkg.domainSpecificDeps.length > 5 ? ", …" : ""})`
            : ""
        }</td>
      </tr>
      <tr>
        <td>Human commits</td>
        <td>${r.tier.features.humanCommitsExist ? "yes" : "no"} (${b.human} human, ${b.total} total)</td>
      </tr>
      <tr>
        <td>Any PR</td>
        <td>${r.tier.features.prsExist ? "yes" : "no"} (${r.prs.count} total, ${r.prs.merged} merged)</td>
      </tr>
      <tr>
        <td>Docs present</td>
        <td>${r.tier.features.docsPresent ? "yes" : "no"}${r.docs.hasClaudeMd ? " (CLAUDE.md)" : ""}${r.docs.hasDocsFolder ? ` (docs/, ${r.docs.docsFileCount} files)` : ""}</td>
      </tr>
    </table>

    ${bucketBits.length > 0 ? `<p><strong>Author breakdown:</strong> ${escapeHtml(bucketBits.join(" · "))}</p>` : ""}

    <p>
      <strong>Publish-button:</strong> ${r.publishButton.score}/100
      ${r.publishButton.flagged ? `<span class="flag">⚑ flagged</span>` : ""}
    </p>
    ${r.publishButton.reasons.length > 0 ? `<ul class="reason-list">${r.publishButton.reasons.map((rr) => `<li>+${rr.points}: ${escapeHtml(rr.reason)}</li>`).join("")}</ul>` : ""}

    ${
      r.resumption.applicable
        ? `<p>
            <strong>Resumption:</strong> ${r.resumption.score}/100
            ${r.resumption.strongCandidate ? `<span class="strong">★ strong candidate</span>` : ""}
            · est. ${r.resumption.estimatedHoursToResume}h
          </p>
          ${r.resumption.reasons.length > 0 ? `<ul class="reason-list">${r.resumption.reasons.map((rr) => `<li>+${rr.points}: ${escapeHtml(rr.reason)}</li>`).join("")}</ul>` : ""}`
        : ""
    }

    <p><strong>AI surface:</strong> ${escapeHtml(r.aiDiversity.toolsDetected.join(", ") || "(none detected)")}</p>
    ${r.aiDiversity.suggestions.length > 0 ? `<ul class="reason-list">${r.aiDiversity.suggestions.map((s) => `<li>${escapeHtml(s)}</li>`).join("")}</ul>` : ""}

    ${
      r.editorialVoice.voiceEscalation !== "absent" || r.editorialVoice.hasResearchCitations
        ? `<p><strong>Editorial voice:</strong> ${r.editorialVoice.voiceEscalation}
           · ${r.editorialVoice.conventionalCommitCount} conventional-commit prefixes
           · ${r.editorialVoice.citationCount} research citation(s)</p>`
        : ""
    }

    <p class="next-step"><strong>Next step:</strong> ${escapeHtml(r.nextStep)}</p>

    ${r.errors.length > 0 ? `<details><summary>Fetch errors (${r.errors.length})</summary><ul>${r.errors.map((e) => `<li>${escapeHtml(e)}</li>`).join("")}</ul></details>` : ""}
  </article>`;
}

// ---------------------------------------------------------------------------
// styles + client script (inline)
// ---------------------------------------------------------------------------

function styles(): string {
  return `
:root {
  --bg: #fafafa;
  --fg: #1a1a1a;
  --muted: #6b7280;
  --card: #ffffff;
  --border: #e5e7eb;
  --tier-a: #16a34a;
  --tier-b: #2563eb;
  --tier-c: #f59e0b;
  --tier-d: #6b7280;
  --flag: #dc2626;
  --strong: #7c3aed;
}
* { box-sizing: border-box; }
body {
  background: var(--bg); color: var(--fg);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  margin: 0; padding: 2rem; max-width: 1200px; margin-inline: auto;
  line-height: 1.5;
}
header h1 { margin-bottom: 0.25rem; }
header .meta { color: var(--muted); margin-top: 0; }
section { background: var(--card); border: 1px solid var(--border); border-radius: 8px;
  padding: 1.5rem; margin-bottom: 1.5rem; }
h2 { margin-top: 0; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }
.tier-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin-bottom: 1rem; }
.tier-card { padding: 1rem; border-radius: 6px; text-align: center; color: white; }
.tier-card.tier-A { background: var(--tier-a); }
.tier-card.tier-B { background: var(--tier-b); }
.tier-card.tier-C { background: var(--tier-c); }
.tier-card.tier-D { background: var(--tier-d); }
.tier-count { font-size: 2.5rem; font-weight: bold; line-height: 1; }
.tier-label { font-weight: 600; margin-top: 0.25rem; }
.tier-sub { font-size: 0.85rem; opacity: 0.9; }
.next-action { background: #f3f4f6; padding: 0.75rem 1rem; border-radius: 6px; margin: 1rem 0; }
.totals { color: var(--muted); }
.insights { line-height: 1.6; }
table { width: 100%; border-collapse: collapse; }
th, td { padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid var(--border); }
th { background: #f9fafb; cursor: pointer; user-select: none; font-weight: 600; }
th:hover { background: #f3f4f6; }
th.sort-asc::after { content: " ▲"; color: var(--muted); }
th.sort-desc::after { content: " ▼"; color: var(--muted); }
.repos-table tbody tr:hover { background: #f9fafb; }
.tier-pill { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 999px;
  font-size: 0.85rem; font-weight: 600; color: white; }
.tier-pill.tier-A { background: var(--tier-a); }
.tier-pill.tier-B { background: var(--tier-b); }
.tier-pill.tier-C { background: var(--tier-c); }
.tier-pill.tier-D { background: var(--tier-d); }
.tool-pill { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 4px;
  font-size: 0.85rem; background: #e5e7eb; color: var(--fg); }
code { background: #f3f4f6; padding: 0.1rem 0.35rem; border-radius: 3px;
  font-size: 0.9em; font-family: "SFMono-Regular", Consolas, monospace; }
.repo-detail { border-top: 1px solid var(--border); padding: 1rem 0; }
.repo-detail:first-of-type { border-top: none; }
.repo-detail h3 { margin-bottom: 0.5rem; }
.repo-desc { color: var(--muted); font-style: italic; }
.repo-meta { font-size: 0.9em; color: var(--muted); }
.rationale { background: #f9fafb; padding: 0.5rem 0.75rem; border-radius: 4px; }
.feature-table { width: auto; min-width: 50%; margin: 0.75rem 0; }
.reason-list { font-size: 0.9em; color: var(--muted); }
.flag { color: var(--flag); font-weight: 600; }
.strong { color: var(--strong); font-weight: 600; }
.next-step { background: #fef3c7; padding: 0.5rem 0.75rem; border-radius: 4px;
  border-left: 3px solid #f59e0b; }
.hint { color: var(--muted); font-size: 0.9em; }
footer { margin-top: 2rem; color: var(--muted); font-size: 0.9em; }
footer a { color: var(--muted); }
`;
}

function clientScript(): string {
  // Tiny vanilla-JS sorter. Stored as a string so the HTML report is single-file.
  return `
(function(){
  var table = document.getElementById('repos-table');
  if (!table) return;
  var ths = table.querySelectorAll('thead th');
  ths.forEach(function(th, idx){
    th.addEventListener('click', function(){
      var type = th.getAttribute('data-sort') || 'string';
      var dir = th.classList.contains('sort-asc') ? 'desc' : 'asc';
      ths.forEach(function(o){ o.classList.remove('sort-asc','sort-desc'); });
      th.classList.add(dir === 'asc' ? 'sort-asc' : 'sort-desc');
      var tbody = table.querySelector('tbody');
      var rows = Array.prototype.slice.call(tbody.querySelectorAll('tr'));
      rows.sort(function(a,b){
        var av = a.children[idx].textContent.trim();
        var bv = b.children[idx].textContent.trim();
        if (type === 'number') {
          var an = parseFloat(av.replace(/[^0-9.\\-]/g,'')) || 0;
          var bn = parseFloat(bv.replace(/[^0-9.\\-]/g,'')) || 0;
          return dir === 'asc' ? an - bn : bn - an;
        }
        return dir === 'asc'
          ? av.localeCompare(bv)
          : bv.localeCompare(av);
      });
      rows.forEach(function(r){ tbody.appendChild(r); });
    });
  });
})();
`;
}

// ---------------------------------------------------------------------------
// escaping
// ---------------------------------------------------------------------------

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeAttr(s: string): string {
  return escapeHtml(s);
}
