/**
 * Markdown report generator.
 *
 * One Markdown file per scan, with three sections:
 *   1. Portfolio summary (counts per tier, hours-to-resume, suggested action)
 *   2. Per-repo detail (tier, all scores, AI tools, next step)
 *   3. Cross-repo insights
 */

import type {
  AiTool,
  PortfolioReport,
  PortfolioSummary,
  RepoAnalysis,
  Tier,
} from "../types.js";

export function renderMarkdownReport(report: PortfolioReport): string {
  const lines: string[] = [];
  lines.push(`# Portfolio Scan Report`);
  lines.push("");
  lines.push(`> Generated by PortfolioPilot Scanner v0.1.0`);
  lines.push("");
  lines.push(`- **User:** \`@${report.summary.username}\``);
  lines.push(`- **Scanned at:** ${report.summary.scannedAt}`);
  lines.push(`- **Total repos scanned:** ${report.summary.totalRepos}`);
  lines.push("");

  renderSummary(lines, report.summary);
  renderTierTable(lines, report.repos);
  renderInsights(lines, report.summary);
  renderRepoDetail(lines, report.repos);
  renderFooter(lines);

  return lines.join("\n");
}

function renderSummary(lines: string[], s: PortfolioSummary): void {
  lines.push(`## Portfolio Summary`);
  lines.push("");
  lines.push(`| Tier | Count | Meaning |`);
  lines.push(`|------|-------|---------|`);
  lines.push(
    `| **A** | ${s.countsByTier.A} | Managed system — continue investment |`,
  );
  lines.push(
    `| **B** | ${s.countsByTier.B} | Developing — has signal, decide resume vs. archive |`,
  );
  lines.push(
    `| **C** | ${s.countsByTier.C} | Prototype-stalled — bot-only or publish-button satisfied |`,
  );
  lines.push(
    `| **D** | ${s.countsByTier.D} | Template skeleton — never developed, archive |`,
  );
  lines.push("");
  lines.push(
    `**Total estimated hours to resume all Tier B/C repos:** ${s.totalEstimatedHoursToResume}h`,
  );
  lines.push("");
  lines.push(`### Suggested next action`);
  lines.push("");
  lines.push(`> ${s.suggestedNextAction}`);
  lines.push("");

  if (s.reposStrongResumptionCandidates.length > 0) {
    lines.push(
      `### Strong resumption candidates (resumption score ≥60)`,
    );
    lines.push("");
    for (const r of s.reposStrongResumptionCandidates) {
      lines.push(`- \`${r}\``);
    }
    lines.push("");
  }

  if (s.reposLikelyPublishButtonSatisfied.length > 0) {
    lines.push(`### Likely publish-button-satisfied (archive candidates)`);
    lines.push("");
    for (const r of s.reposLikelyPublishButtonSatisfied) {
      lines.push(`- \`${r}\``);
    }
    lines.push("");
  }

  // AI tool coverage
  const toolsWithRepos = (Object.entries(s.reposByAiTool) as [AiTool, string[]][]).filter(
    ([, repos]) => repos.length > 0,
  );
  if (toolsWithRepos.length > 0) {
    lines.push(`### AI tool coverage across portfolio`);
    lines.push("");
    lines.push(`| Tool | Repo count | Repos |`);
    lines.push(`|------|------------|-------|`);
    for (const [tool, repos] of toolsWithRepos) {
      const shown = repos.slice(0, 5).join(", ");
      const suffix = repos.length > 5 ? `, +${repos.length - 5}` : "";
      lines.push(`| ${tool} | ${repos.length} | ${shown}${suffix} |`);
    }
    lines.push("");
  }
}

function renderTierTable(lines: string[], repos: RepoAnalysis[]): void {
  lines.push(`## All Repos (sorted by tier, then score)`);
  lines.push("");
  lines.push(
    `| Repo | Tier | Score | Last commit (d) | Publish-btn | Resume | AI tools |`,
  );
  lines.push(
    `|------|------|-------|-----------------|-------------|--------|----------|`,
  );

  const sorted = [...repos].sort((a, b) => {
    const tierOrder: Record<Tier, number> = { A: 0, B: 1, C: 2, D: 3 };
    if (tierOrder[a.tier.tier] !== tierOrder[b.tier.tier]) {
      return tierOrder[a.tier.tier] - tierOrder[b.tier.tier];
    }
    return b.tier.score - a.tier.score;
  });

  for (const r of sorted) {
    const days = r.commits.daysSinceLastCommit;
    const pb = `${r.publishButton.score}${r.publishButton.flagged ? " ⚑" : ""}`;
    const resume = r.resumption.applicable
      ? `${r.resumption.score}${r.resumption.strongCandidate ? " ★" : ""}`
      : "—";
    const tools = r.aiDiversity.toolsDetected.join(", ") || "—";
    lines.push(
      `| \`${r.metadata.name}\` | ${r.tier.tier} | ${r.tier.score}/4 | ${days} | ${pb} | ${resume} | ${tools} |`,
    );
  }
  lines.push("");
}

function renderInsights(lines: string[], s: PortfolioSummary): void {
  if (s.insights.length === 0) return;
  lines.push(`## Cross-repo insights`);
  lines.push("");
  for (const i of s.insights) {
    lines.push(`- ${i}`);
  }
  lines.push("");
}

function renderRepoDetail(lines: string[], repos: RepoAnalysis[]): void {
  lines.push(`## Per-repo detail`);
  lines.push("");

  const sorted = [...repos].sort((a, b) => {
    const tierOrder: Record<Tier, number> = { A: 0, B: 1, C: 2, D: 3 };
    if (tierOrder[a.tier.tier] !== tierOrder[b.tier.tier]) {
      return tierOrder[a.tier.tier] - tierOrder[b.tier.tier];
    }
    return b.tier.score - a.tier.score;
  });

  for (const r of sorted) {
    renderSingleRepo(lines, r);
  }
}

function renderSingleRepo(lines: string[], r: RepoAnalysis): void {
  lines.push(`### \`${r.metadata.name}\` — Tier ${r.tier.tier} (${r.tier.score}/4)`);
  lines.push("");
  if (r.metadata.description) {
    lines.push(`> ${r.metadata.description}`);
    lines.push("");
  }
  lines.push(`- **URL:** ${r.metadata.htmlUrl}`);
  lines.push(
    `- **Default branch:** \`${r.metadata.defaultBranch}\` · **Private:** ${r.metadata.isPrivate} · **Fork:** ${r.metadata.isFork} · **Archived:** ${r.metadata.isArchived}`,
  );
  lines.push(
    `- **Last commit:** ${r.commits.lastCommitDate ?? "n/a"} (${r.commits.daysSinceLastCommit} days ago)`,
  );
  const langs = Object.keys(r.metadata.languages).slice(0, 3).join(", ");
  if (langs) lines.push(`- **Languages:** ${langs}`);
  lines.push("");

  lines.push(`**Tier rationale:** ${r.tier.rationale}`);
  lines.push("");

  // Features table
  lines.push(`| Feature | Status |`);
  lines.push(`|---------|--------|`);
  lines.push(
    `| Non-template deps | ${r.tier.features.hasNonTemplateDeps ? "yes" : "no"}${r.pkg.domainSpecificDeps.length > 0 ? ` (${r.pkg.domainSpecificDeps.slice(0, 5).join(", ")}${r.pkg.domainSpecificDeps.length > 5 ? ", …" : ""})` : ""} |`,
  );
  lines.push(
    `| Human commits | ${r.tier.features.humanCommitsExist ? "yes" : "no"} (${r.commits.buckets.human} human, ${r.commits.buckets.total} total) |`,
  );
  lines.push(
    `| Any PR | ${r.tier.features.prsExist ? "yes" : "no"} (${r.prs.count} total, ${r.prs.merged} merged) |`,
  );
  lines.push(
    `| Docs present | ${r.tier.features.docsPresent ? "yes" : "no"}${r.docs.hasClaudeMd ? " (CLAUDE.md)" : ""}${r.docs.hasDocsFolder ? ` (docs/, ${r.docs.docsFileCount} files)` : ""}${!r.docs.hasClaudeMd && !r.docs.hasDocsFolder && r.readme.isSubstantial ? " (substantial README)" : ""} |`,
  );
  lines.push("");

  // Author breakdown
  const b = r.commits.buckets;
  const bucketBits: string[] = [];
  if (b.human) bucketBits.push(`human ${b.human}`);
  if (b.claude) bucketBits.push(`claude ${b.claude}`);
  if (b["claude-coauthored"])
    bucketBits.push(`claude-coauthored ${b["claude-coauthored"]}`);
  if (b.cursor) bucketBits.push(`cursor ${b.cursor}`);
  if (b.lovable) bucketBits.push(`lovable ${b.lovable}`);
  if (b["gpt-engineer"]) bucketBits.push(`gpt-engineer ${b["gpt-engineer"]}`);
  if (b["bolt-bot"]) bucketBits.push(`bolt ${b["bolt-bot"]}`);
  if (b["v0-bot"]) bucketBits.push(`v0 ${b["v0-bot"]}`);
  if (b.codex) bucketBits.push(`codex ${b.codex}`);
  if (b.copilot) bucketBits.push(`copilot ${b.copilot}`);
  if (b["bot-other"]) bucketBits.push(`other-bot ${b["bot-other"]}`);
  if (bucketBits.length > 0) {
    lines.push(`**Commit author breakdown:** ${bucketBits.join(" · ")}`);
    lines.push("");
  }

  // Publish-button
  lines.push(
    `**Publish-button satisfiability:** ${r.publishButton.score}/100 ${r.publishButton.flagged ? "⚑ flagged" : ""}`,
  );
  if (r.publishButton.reasons.length > 0) {
    for (const reason of r.publishButton.reasons) {
      lines.push(`  - +${reason.points}: ${reason.reason}`);
    }
  }
  lines.push("");

  // Resumption
  if (r.resumption.applicable) {
    lines.push(
      `**Resumption readiness:** ${r.resumption.score}/100 ${r.resumption.strongCandidate ? "★ strong candidate" : ""} · est. ${r.resumption.estimatedHoursToResume}h to resume`,
    );
    for (const reason of r.resumption.reasons) {
      lines.push(`  - +${reason.points}: ${reason.reason}`);
    }
    lines.push("");
  }

  // AI diversity
  lines.push(
    `**AI surface:** ${r.aiDiversity.toolsDetected.join(", ") || "(none detected)"}`,
  );
  for (const s of r.aiDiversity.suggestions) {
    lines.push(`  - ${s}`);
  }
  lines.push("");

  // Editorial voice (only mention if interesting)
  if (
    r.editorialVoice.voiceEscalation !== "absent" ||
    r.editorialVoice.hasResearchCitations
  ) {
    lines.push(
      `**Editorial voice:** ${r.editorialVoice.voiceEscalation}` +
        ` · ${r.editorialVoice.conventionalCommitCount} conventional-commit prefixes` +
        ` · ${r.editorialVoice.citationCount} research citation(s) in bodies`,
    );
    lines.push("");
  }

  // Next step
  lines.push(`**Next step:** ${r.nextStep}`);
  lines.push("");

  // Errors
  if (r.errors.length > 0) {
    lines.push(`**Fetch errors:**`);
    for (const e of r.errors) lines.push(`  - ${e}`);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
}

function renderFooter(lines: string[]): void {
  lines.push(`## How to interpret`);
  lines.push("");
  lines.push(
    "- **Tier A**: Mature managed system. Continue investment; treat as production-grade. Don't be afraid to keep adding CLAUDE.md / LOG.md / docs/ scaffolding here.",
  );
  lines.push(
    "- **Tier B**: Resumed prototype with real signal. Decide explicitly: run the 72-minute resumer sprint (`/products/playbooks/resumer-day-prep.md`) or archive after one final classifier review.",
  );
  lines.push(
    "- **Tier C**: Prototype-stalled or publish-button-satisfied. Probably finished by its own success condition — archive without guilt.",
  );
  lines.push(
    "- **Tier D**: Never-developed template skeleton. Archive immediately.",
  );
  lines.push("");
  lines.push(
    "- **Publish-button ⚑**: Score ≥50 means the repo's last activity looks like the operator pressed Lovable's Publish button and never came back. Read `/products/playbooks/publish-button-intent-triage.md` before reviving.",
  );
  lines.push(
    "- **Resumption ★**: Score ≥60 means the repo is a strong candidate for a 72-minute sprint. Domain dep + recent commit + filled README all present.",
  );
  lines.push("");
}
