import type { ProjectSpec, ScaffoldFile } from './types'

export function renderCLAUDE(spec: ProjectSpec): string {
  return `# CLAUDE.md — ${spec.meta.name}

> Gate 0 protocol for the ${spec.meta.name} project.
> Generated by Genesis (RepoHealth forward mode) on ${spec.meta.createdAt.split('T')[0]}.

## Project context

${spec.meta.description}

- **Domain**: ${spec.meta.domain}
- **Language**: ${spec.meta.language === 'he' ? 'Hebrew (RTL, Hebrew-first vocabulary)' : spec.meta.language}
- **Tier A contract**: see \`.claude/tier-a.contract.yml\`
- **Ontology (frozen IR)**: see \`.claude/ontology.json\`

## Gate 0 — Before any code change

1. Read \`docs/spec.md\` to refresh the entity model + invariants
2. Identify which entity or transaction this change affects
3. Cite the affected entity in the commit message (target: >=30% of commits cite an entity)
4. If introducing a new dependency, add a justification comment in \`package.json\`
5. If touching a documented invariant, update \`LOG.md\` with the reasoning

## Anti-patterns — DO NOT do these

${spec.antiPatterns
    .map((ap, i) => `### ${i + 1}. ${ap.name} (severity: ${ap.severity})

${ap.description}

**Affected entity**: \`${ap.citesEntity}\``)
    .join('\n\n')}

## Vocabulary table — Domain terms (use these, not the generic terms)

| Domain term | Avoid (generic) | Meaning |
|-------------|-----------------|---------|
${spec.vocabulary.map(v => `| ${v.domainTerm} | ${v.genericTerm} | ${v.definition} |`).join('\n')}

## Invariants — Always true

${spec.invariants
    .map(inv => `- **${inv.id}** (${inv.scope}, ${inv.severity}): ${inv.statement}`)
    .join('\n')}

## Editorial voice — Commit message style

**Good** (cite entities, distinguish domain terms):
${spec.voiceSamples.good.map(s => `- ${s}`).join('\n')}

**Bad** (avoid these patterns):
${spec.voiceSamples.bad.map(s => `- ${s}`).join('\n')}

## How to check this project's health

The Tier A contract that generated this project also audits it on every push.
Drift alerts arrive in your RepoHealth dashboard.
`
}

export function renderLOG(spec: ProjectSpec): string {
  return `# LOG.md — ${spec.meta.name}

> Human-skeleton anti-pattern log + decision history.
> This file is human-authored. Bots may suggest entries but humans confirm them.

## Environment

- Created: ${spec.meta.createdAt}
- Domain: ${spec.meta.domain}
- Language: ${spec.meta.language}
- Generator: Genesis CLI (RepoHealth forward mode)

## Anti-patterns (carried over from genesis — confirm or remove as you encounter them in code)

${spec.antiPatterns
    .map((ap, i) => `### ${i + 1}. ${ap.name}

- **Severity**: ${ap.severity}
- **Affects**: ${ap.citesEntity}
- **Description**: ${ap.description}
- **First observed in**: genesis (no live observation yet)
- **Mitigation**: _to be filled when first encountered in code_`)
    .join('\n\n')}

## Invariants (declarative, hard)

${spec.invariants.map(inv => `- **${inv.id}** (${inv.scope}): ${inv.statement}`).join('\n')}

## Session history

Add a section per significant work session with the date, what was tried, and what was learned.

### ${spec.meta.createdAt.split('T')[0]} — Project genesis

- Genesis scaffold compiled successfully
- Sharpness validation: passed (see \`.claude/tier-a.contract.yml\`)
- Next: first feature implementation — refer to docs/spec.md for the entity model
`
}

export function renderREADME(spec: ProjectSpec): string {
  return `# ${spec.meta.name}

${spec.meta.description}

## What this is

\`${spec.meta.name}\` is a ${spec.meta.domain} project, generated as Tier A by construction.
Before contributing, read \`CLAUDE.md\` (Gate 0 protocol) and \`docs/spec.md\` (entity model).

## Entities

${spec.entities.map(e => `- **${e.name}**${e.hebrewName ? ` (${e.hebrewName})` : ''}${e.ownedBy ? ` — owned by ${e.ownedBy}` : ''}`).join('\n')}

## Actors

${spec.actors.map(a => `- **${a.name}** — ${a.role} (${a.frequency}, ${a.criticality})`).join('\n')}

## Tier A contract

This project carries a \`.claude/tier-a.contract.yml\` defining:

- **F1**: non-template dependencies (each justified in \`package.json\`)
- **F2**: human commits required before deploy (>=3)
- **F3**: PR-based workflow (direct-to-main blocked)
- **F4**: CLAUDE.md + LOG.md + docs/ all present

Drift from this contract is detected automatically on every RepoHealth scan.

## Getting started

\`\`\`sh
pnpm install
pnpm dev
\`\`\`

## License

MIT (or replace with your license)
`
}

export function renderSpec(spec: ProjectSpec): string {
  return `# Spec — ${spec.meta.name}

## Description

${spec.meta.description}

## Entity model

${spec.entities
    .map(e => `### ${e.name}${e.hebrewName ? ` (${e.hebrewName})` : ''}

- **Plural**: ${e.plural}
- **Owned by**: ${e.ownedBy ?? '(root)'}`)
    .join('\n\n')}

## Transactions

${spec.transactions
    .map(t => `- \`${t.verb}(${t.subject} -> ${t.object})\` — guards: ${t.invariantRefs.join(', ')}`)
    .join('\n')}

## Invariants

${spec.invariants
    .map(inv => `### ${inv.id} (${inv.severity})

**Scope**: ${inv.scope}

${inv.statement}`)
    .join('\n\n')}

## Vocabulary

| Domain | Generic (avoid) | Meaning |
|--------|-----------------|---------|
${spec.vocabulary.map(v => `| ${v.domainTerm} | ${v.genericTerm} | ${v.definition} |`).join('\n')}

## Anti-patterns

${spec.antiPatterns
    .map(ap => `### ${ap.name} (${ap.severity})

**Affects**: ${ap.citesEntity}

${ap.description}`)
    .join('\n\n')}
`
}

export function renderPackageJson(spec: ProjectSpec): string {
  const obj = {
    name: spec.meta.name,
    version: '0.0.1',
    private: true,
    description: spec.meta.description,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
    },
    dependencies: {
      next: '^14.2.0',
      react: '^18.3.0',
      'react-dom': '^18.3.0',
    },
    devDependencies: {
      typescript: '^5.4.0',
      '@types/node': '^20.0.0',
      '@types/react': '^18.3.0',
      '@types/react-dom': '^18.3.0',
    },
    'tier-a': {
      contract: '.claude/tier-a.contract.yml',
      ontology: '.claude/ontology.json',
      'dependency-justifications': {
        next: 'F1: chosen framework for SSR + App Router',
        react: 'F1: required peer of next',
        'react-dom': 'F1: required peer of next',
      },
    },
  }
  return JSON.stringify(obj, null, 2) + '\n'
}

export function renderOntology(spec: ProjectSpec): string {
  return JSON.stringify(spec, null, 2) + '\n'
}

export function renderContractYml(spec: ProjectSpec): string {
  return `contract_version: 1
project:
  name: "${spec.meta.name}"
  domain: "${spec.meta.domain}"
  language: "${spec.meta.language}"

tier_a_requirements:
  f1_non_template_deps:
    required: true
    justification_required_per_dep: true
  f2_human_commit:
    enforced_via: checkpoint_prompts
    min_human_commits_before_deploy: 3
  f3_pull_requests:
    default_workflow: feature_branch_pr
    direct_to_main_blocked: true
  f4_documentation:
    claude_md: required
    log_md: required
    docs_dir: required_with_min_one_file

sharpness:
  anti_patterns:
    min_items: 3
    forbidden_phrases:
      - generic
      - follow best practices
      - avoid bugs
      - improve quality
    must_cite_entity: true
  invariants:
    min_items: 2
    form: declarative
  vocabulary:
    min_substitutions: 3
  voice:
    citation_density_min: 0.3
    bad_samples_min: 2

entities:
${spec.entities.map(e => `  - ${e.name}`).join('\n')}
`
}

export function renderAll(spec: ProjectSpec): ScaffoldFile[] {
  return [
    { path: 'CLAUDE.md',                   content: renderCLAUDE(spec) },
    { path: 'LOG.md',                      content: renderLOG(spec) },
    { path: 'README.md',                   content: renderREADME(spec) },
    { path: 'package.json',                content: renderPackageJson(spec) },
    { path: 'docs/spec.md',                content: renderSpec(spec) },
    { path: '.claude/ontology.json',       content: renderOntology(spec) },
    { path: '.claude/tier-a.contract.yml', content: renderContractYml(spec) },
  ]
}
